export const timezones = [
    { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
    { value: 'America/New_York', label: 'Eastern Time (US & Canada)' },
    { value: 'America/Chicago', label: 'Central Time (US & Canada)' },
    { value: 'America/Denver', label: 'Mountain Time (US & Canada)' },
    { value: 'America/Los_Angeles', label: 'Pacific Time (US & Canada)' },
    { value: 'America/Anchorage', label: 'Alaska' },
    { value: 'Pacific/Honolulu', label: 'Hawaii' },
    { value: 'Europe/London', label: 'London, Edinburgh, Dublin' },
    { value: 'Europe/Paris', label: 'Paris, Berlin, Rome, Madrid' },
    { value: 'Europe/Moscow', label: 'Moscow, St. Petersburg' },
    { value: 'Asia/Dubai', label: 'Dubai, Abu Dhabi' },
    { value: 'Asia/Karachi', label: 'Islamabad, Karachi' },
    { value: 'Asia/Colombo', label: 'Sri Lanka (Colombo)' },
    { value: 'Asia/Kolkata', label: 'Chennai, Kolkata, Mumbai, New Delhi' },
    { value: 'Asia/Dhaka', label: 'Dhaka' },
    { value: 'Asia/Bangkok', label: 'Bangkok, Hanoi, Jakarta' },
    { value: 'Asia/Singapore', label: 'Singapore, Kuala Lumpur' },
    { value: 'Asia/Shanghai', label: 'Beijing, Shanghai, Hong Kong' },
    { value: 'Asia/Tokyo', label: 'Tokyo, Seoul, Osaka' },
    { value: 'Australia/Sydney', label: 'Sydney, Melbourne, Canberra' },
    { value: 'Pacific/Auckland', label: 'Auckland, Wellington' },
];

export const countries = [
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "India",
    "Pakistan",
    "United Arab Emirates",
    "Saudi Arabia",
    "China",
    "Japan",
    "Germany",
    "France",
    "Brazil",
    "Mexico",
    "Russia",
    "South Africa",
    "Nigeria",
    "Egypt",
    "Indonesia",
    "Malaysia",
    "Singapore",
    "Thailand",
    "Vietnam",
    "Philippines",
    "South Korea",
    "Bangladesh",
];
