-- Database is selected by active connection

INSERT IGNORE INTO settings (`key`, value, category, data_type) VALUES
  ('company_name', 'Azytion GemERP', 'company', 'string'),
  ('company_address', '', 'company', 'string'),
  ('company_phone', '+94752723544', 'company', 'string'),
  ('company_phone_2', '+94755331445', 'company', 'string'),
  ('company_email', 'azytionlk@gmail.com', 'company', 'string'),
  ('company_website', 'www.azytion.com', 'company', 'string'),
  ('company_tax_id', '', 'company', 'string'),
  ('company_logo', '', 'company', 'string'),
  ('tax_enabled', 'false', 'tax', 'boolean'),
  ('tax_rate', '0', 'tax', 'number'),
  ('tax_name', 'Tax', 'tax', 'string'),
  ('tax_inclusive', 'false', 'tax', 'boolean'),
  ('receipt_header', '', 'receipt', 'string'),
  ('receipt_footer', 'Thank you for your business!', 'receipt', 'string'),
  ('receipt_promotional_footer', 'Powered By Azytion | +94752723544', 'receipt', 'string'),
  ('receipt_show_logo', 'true', 'receipt', 'boolean'),
  ('receipt_show_barcode', 'true', 'receipt', 'boolean'),
  ('receipt_paper_size', 'a4', 'receipt', 'string'),
  ('currency_symbol', '$', 'system', 'string'),
  ('currency_code', 'USD', 'system', 'string'),
  ('exchange_rates_enabled', 'false', 'system', 'boolean'),
  ('exchange_display_currency', '', 'system', 'string'),
  ('exchange_rates', '[]', 'system', 'json'),
  ('date_format', 'MM/DD/YYYY', 'system', 'string'),
  ('time_format', '12h', 'system', 'string'),
  ('low_stock_threshold', '10', 'system', 'number'),
  ('last_auto_export_date', '', 'system', 'string'),
  ('email_notifications', 'true', 'notification', 'boolean'),
  ('low_stock_alerts', 'true', 'notification', 'boolean'),
  ('smtp_host', '', 'notification', 'string'),
  ('smtp_port', '587', 'notification', 'number'),
  ('smtp_user', '', 'notification', 'string'),
  ('smtp_pass', '', 'notification', 'string'),
  ('smtp_secure', 'false', 'notification', 'boolean'),
  ('email_from', '"Azytion GemERP" <noreply@azytionapp.com>', 'notification', 'string'),
  ('pos_auto_discount_enabled', 'false', 'pos', 'boolean'),
  ('pos_auto_print_enabled', 'true', 'pos', 'boolean'),
  ('pos_auto_print_format', 'a4', 'pos', 'string'),
  ('pos_product_images_enabled', 'true', 'pos', 'boolean'),
  ('printer_method', 'a4_pdf', 'pos', 'string'),
  ('system_printer_name', '', 'pos', 'string'),
  ('subscription_status', 'active', 'subscription', 'string'),
  ('subscription_expiry', '', 'subscription', 'string'),
  ('client_name', 'Valued Client', 'subscription', 'string');
